config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"

  post '/', controller: :welcome, action: :search
  get '/show', controller: :welcome, action: :search

  namespace :users do
    resources :manage, controller: :manage, only: :index
  end
  namespace :products do
    resources :manage, controller: :manage
  end
  namespace :orders do
    resources :manage, controller: :manage
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  HASHIDS = Hashids.new(Rails.application.secrets[:secret_key_base] + 'Order', 8, ('A'..'Z').to_a.join)

  belongs_to :user
  has_many :order_items, inverse_of: :order
  has_many :products, through: :order_items

  accepts_nested_attributes_for :order_items, allow_destroy: true

  def auth_token
    @auth_token ||= HASHIDS.encode(rand(10**7)).first(8)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :count, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :check_quantity

  after_validation :change_count

  private

  def check_quantity
    errors.add(:count, "No such quantity of product in storehouse") if
      (unless direction == 'on'
        Product.find(product_id).count < count
      end)
  end

  def change_count
    product = Product.find(product_id)
    if direction == 'on'
      product.count = product.count + count
    else
      product.count = product.count - count
    end
    begin
      product.save
    rescue ActiveRecord::StaleObjectError
      change_count
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items

  validates :title, uniqueness: true, presence: true

  has_attached_file :image, styles: { medium: "150x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  default_value_for :admin, false

  scope :not_admins, -> { where(admin: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  skip_before_filter :authenticate_user!, only: [:index, :search]

  protected

  def after_invite_path_for(inviter, invitee)
    users_manage_index_path
  end

  def authenticate_inviter!
    authenticate_user!(:force => true)
    authorize_admin!
  end

  private

  def authorize_admin!
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/orders/manage_controller.rb
module Orders
  class ManageController < ApplicationController
    before_action :authorize_admin!, only: [:index]

    def index
      @orders = Order.all
    end

    def show
      @orders = current_user.orders.all
    end

    def new
      @order = current_user.orders.new
      @order.order_items.build
    end

    def create
      @order = current_user.orders.new(order_params)
      @order.token = @order.auth_token
      if @order.save
        flash[:notice] = t('orders.created')
        redirect_to orders_manage_path(id: current_user.id)
      else
        render :new
      end
    end

    private
    def order_params
      params.require(:order).permit(order_items_attributes: [:id, :_destroy, :product_id, :count, :direction])
    end
  end
end

app/controllers/products/manage_controller.rb
module Products
  class ManageController < ApplicationController
    before_action :authorize_admin!

    def index
      @products = Product.all
    end

    def new
      @product = Product.new
    end

    def edit
      @product = Product.find(params[:id])
    end

    def create
      @product = Product.new(product_params)
      @product.count = 0
      if @product.save
        flash[:notice] = t('products.created')
        redirect_to action: :index
      else
        render :new
      end
    end

    def update
      if @product.update(product_params)
        flash[:notice] = t('products.updted')
        redirect_to action: :index
      else
        render :edit
      end
    end

    private
    def product_params
      params.require(:product).permit(:title, :image)
    end
  end
end

app/controllers/users/manage_controller.rb
module Users
  class ManageController < ApplicationController
    before_action :authorize_admin!

    def index
      @resources = User.not_admins
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def search
    @order = Order.find_by('token= ?', params['/show'][:search])
    if !@order.nil?
      @order_item = OrderItem.where('order_id = ?', @order.id)
    else
      flash[:error] = t('orders.not_found')
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestStorehouse
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          .navbar-brand= link_to t('company'), root_path
        #navbar.navbar-collapse.collapse
          - if user_signed_in? && current_user.admin?
            %ul.nav.navbar-nav
              %li= link_to t('products.new'), new_products_manage_path
              %li= link_to t('products.all'), products_manage_index_path
              %li= link_to t('orders.all'), orders_manage_index_path
          %ul.nav.navbar-nav.navbar-right
            %li
            - if user_signed_in?
              - if current_user.admin?
                %li= link_to t('users.manage.index_button'), users_manage_index_path
              - else
                %li= link_to t('orders.new'), new_orders_manage_path
                %li= link_to t('orders.all'), orders_manage_path(id: current_user.id)
              %li= link_to t('sign.out'), destroy_user_session_path, :method => :delete
            -else
              %li= link_to t('sign.in'), new_user_session_path
    = yield

app/views/welcome/index.html.haml
%h1= t('welcome')
%br
= simple_form_for show_path, method: :post do |f|
  = f.input :search, label: t('orders.token')
  = f.submit  t('orders.find'), class: 'btn btn-success'

app/views/welcome/search.html.haml
%h1= t('orders.show')

%p
  = t('orders.token')
  = @order.token

%h3= t('orders.item.all')
- @order_item.each do |ord|
  %h5= t('orders.item.title')
  = ord.product.title
  %h5= t('orders.item.count')
  = ord.count
  %h5= t('orders.item.direction')
  = ord.direction
%br
= link_to t('back'), root_path, class: 'btn btn-primary'